### ISSUE TITLE
composer lose Vendor folder

### ISSUE THREAD

**Issue by samreachyan** [drehimself/laravel-vue-spa#1]
when I clone your project into my directory. I cannot use composer install to get vendor folder. My composer not error but not support your vue-spa. I dont know why. I can use composer to download laravel ( it's also download vendor folder normally) except laravel-vue-spa. 
npm install (working normally). 

vendor folder in composer not download, I cannot migrate DB. cannot start project. Do you have any recommendations.? Thanks​ you in advance

**Comment by wbarnard81** [comment]
I have not had this issue. Would you mind sharing the error you are getting when running composer install?

**Comment by wbarnard81** [comment]
> when I clone your project into my directory. I cannot use composer install to get vendor folder. My composer not error but not support your vue-spa. I dont know why. I can use composer to download laravel ( it's also download vendor folder normally) except laravel-vue-spa.
> npm install (working normally).
> 
> vendor folder in composer not download, I cannot migrate DB. cannot start project. Do you have any recommendations.? Thanks​ you in advance

I have not had this issue. Would you mind sharing the error you are getting when running composer install?

**Comment by samreachyan** [comment]
Now i fixed. for my experience I cannot download "vendor" folder with this commend "composer install ". to fix this I run "composer install --ignore-platform-reqs" it will download vendor folder.
